//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSYSweb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LSYSEntities3 : DbContext
    {
        public LSYSEntities3()
            : base("name=LSYSEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BAKIM> TBL_BAKIM { get; set; }
        public virtual DbSet<TBL_BAYI> TBL_BAYI { get; set; }
        public virtual DbSet<TBL_FIRMA> TBL_FIRMA { get; set; }
        public virtual DbSet<TBL_HAMMADDE> TBL_HAMMADDE { get; set; }
        public virtual DbSet<TBL_K_HAMMADELER> TBL_K_HAMMADELER { get; set; }
        public virtual DbSet<TBL_MUSTERI> TBL_MUSTERI { get; set; }
        public virtual DbSet<TBL_ODEME> TBL_ODEME { get; set; }
        public virtual DbSet<TBL_SIPARIS> TBL_SIPARIS { get; set; }
        public virtual DbSet<TBL_URUN> TBL_URUN { get; set; }
        public virtual DbSet<TBL_YONETICI> TBL_YONETICI { get; set; }
        public virtual DbSet<TBL_M_URUNLER> TBL_M_URUNLER { get; set; }
        public virtual DbSet<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
