//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSYSweb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FIRMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FIRMA()
        {
            this.TBL_BAYI = new HashSet<TBL_BAYI>();
            this.TBL_ODEME = new HashSet<TBL_ODEME>();
            this.TBL_SIPARIS = new HashSet<TBL_SIPARIS>();
            this.TBL_YONETICI1 = new HashSet<TBL_YONETICI>();
        }
    
        public int FIRMA_ID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string FIRMA_ADI { get; set; }
        public Nullable<int> YONETICI_ID { get; set; }
        public string TELEFON { get; set; }
        public string ADRES { get; set; }
        public string MAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BAYI> TBL_BAYI { get; set; }
        public virtual TBL_YONETICI TBL_YONETICI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ODEME> TBL_ODEME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SIPARIS> TBL_SIPARIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_YONETICI> TBL_YONETICI1 { get; set; }
    }
}
