//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSYSweb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_K_HAMMADELER
    {
        public int K_HAMMADELER_ID { get; set; }
        public Nullable<int> HAMMADDE_ID { get; set; }
        public string HAMMADDE_ADI { get; set; }
        public Nullable<int> URUN_ID { get; set; }
    
        public virtual TBL_HAMMADDE TBL_HAMMADDE { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
