//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSYSweb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_URUNLER
    {
        public int M_URUNLER_ID { get; set; }
        public Nullable<int> MUSTERI_ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public string P_BAKIM_SURESI { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
