//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSYSweb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIPARIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SIPARIS()
        {
            this.TBL_ODEME = new HashSet<TBL_ODEME>();
        }
    
        public int SIPARIS_ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<int> BAYI_ID { get; set; }
        public Nullable<int> URUN_ADET { get; set; }
        public string TARIH { get; set; }
        public Nullable<int> ALIS_FIYAT { get; set; }
        public Nullable<int> TUTAR { get; set; }
        public Nullable<int> TEMIN_SURESI { get; set; }
        public Nullable<int> FIRMA_ID { get; set; }
        public string BAYI_ADI { get; set; }
        public string URUN_ADI { get; set; }
        public Nullable<int> FIYAT { get; set; }
    
        public virtual TBL_BAYI TBL_BAYI { get; set; }
        public virtual TBL_FIRMA TBL_FIRMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ODEME> TBL_ODEME { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
