//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSYS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YONETICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YONETICI()
        {
            this.TBL_FIRMA = new HashSet<TBL_FIRMA>();
        }
    
        public int YONETICI_ID { get; set; }
        public Nullable<int> FIRMA_ID { get; set; }
        public string YONETICI_AD { get; set; }
        public string YONETICI_SOYAD { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SIFRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FIRMA> TBL_FIRMA { get; set; }
        public virtual TBL_FIRMA TBL_FIRMA1 { get; set; }
    }
}
